/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serial4j_core_terminal_NativeFilePermissions */

#ifndef _Included_com_serial4j_core_terminal_NativeFilePermissions
#define _Included_com_serial4j_core_terminal_NativeFilePermissions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serial4j_core_terminal_NativeFilePermissions
 * Method:    getReadOnly
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_NativeFilePermissions_getReadOnly
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_NativeFilePermissions
 * Method:    getWriteOnly
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_NativeFilePermissions_getWriteOnly
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_NativeFilePermissions
 * Method:    getReadWrite
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_NativeFilePermissions_getReadWrite
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_NativeFilePermissions
 * Method:    getNoControlTerminalDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_NativeFilePermissions_getNoControlTerminalDevice
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_NativeFilePermissions
 * Method:    getTerminalNonBlock
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_NativeFilePermissions_getTerminalNonBlock
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_NativeFilePermissions
 * Method:    getCreateFile
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_NativeFilePermissions_getCreateFile
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
