/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits */

#ifndef _Included_com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
#define _Included_com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud0
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud50
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud50
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud75
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud75
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud110
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud110
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud134
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud134
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud150
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud150
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud200
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud200
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud300
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud300
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud600
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud600
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud1200
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud1200
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud1800
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud1800
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud2400
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud2400
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud4800
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud4800
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud9600
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud9600
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud19200
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud19200
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud38400
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud38400
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud57600
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud57600
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud115200
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud115200
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud230400
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud230400
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud460800
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud460800
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud500000
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud500000
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud576000
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud576000
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud921600
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud921600
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud1000000
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud1000000
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud1152000
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud1152000
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud1500000
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud1500000
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud2000000
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud2000000
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud2500000
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud2500000
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud3000000
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud3000000
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud3500000
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud3500000
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getBaud4000000
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getBaud4000000
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getCharacterSize5bits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getCharacterSize5bits
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getCharacterSize6bits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getCharacterSize6bits
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getCharacterSize7bits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getCharacterSize7bits
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags_MaskBits
 * Method:    getCharacterSize8bits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_00024MaskBits_getCharacterSize8bits
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
