/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags */

#ifndef _Included_com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags
#define _Included_com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags
 * Method:    getBackspaceDelayMask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_getBackspaceDelayMask
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags
 * Method:    getCarriageReturnDelayMask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_getCarriageReturnDelayMask
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags
 * Method:    getFormFeedDelayMask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_getFormFeedDelayMask
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags
 * Method:    getNewLineDelayMask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_getNewLineDelayMask
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags
 * Method:    getMapCarriageReturnToNewLine
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_getMapCarriageReturnToNewLine
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags
 * Method:    getUsePredefinedFillCharacters
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_getUsePredefinedFillCharacters
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags
 * Method:    getUseFillCharacters
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_getUseFillCharacters
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags
 * Method:    getMapLowercaseToUppercase
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_getMapLowercaseToUppercase
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags
 * Method:    getMapNewLineToCarriageReturn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_getMapNewLineToCarriageReturn
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags
 * Method:    getNewLineAsCarriageReturn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_getNewLineAsCarriageReturn
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags
 * Method:    getNoCarriageReturnDuplicateOutput
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_getNoCarriageReturnDuplicateOutput
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags
 * Method:    getPerformOutputPostProcessing
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_getPerformOutputPostProcessing
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags
 * Method:    getHorizontalTabDelayMask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_getHorizontalTabDelayMask
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags
 * Method:    getVerticalTabDelayMask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_getVerticalTabDelayMask
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
