/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serial4j_core_modem_NativeModemBits */

#ifndef _Included_com_serial4j_core_modem_NativeModemBits
#define _Included_com_serial4j_core_modem_NativeModemBits
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serial4j_core_modem_NativeModemBits
 * Method:    getDatasetReadyLineEnable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_modem_NativeModemBits_getDatasetReadyLineEnable
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_modem_NativeModemBits
 * Method:    getDataTerminalReady
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_modem_NativeModemBits_getDataTerminalReady
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_modem_NativeModemBits
 * Method:    getRequestToSend
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_modem_NativeModemBits_getRequestToSend
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_modem_NativeModemBits
 * Method:    getSecondaryTransmit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_modem_NativeModemBits_getSecondaryTransmit
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_modem_NativeModemBits
 * Method:    getSecondaryReceive
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_modem_NativeModemBits_getSecondaryReceive
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_modem_NativeModemBits
 * Method:    getClearToSend
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_modem_NativeModemBits_getClearToSend
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_modem_NativeModemBits
 * Method:    getDataCarrierDetect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_modem_NativeModemBits_getDataCarrierDetect
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_modem_NativeModemBits
 * Method:    getRingSignal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_modem_NativeModemBits_getRingSignal
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_modem_NativeModemBits
 * Method:    getDataSetReady
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_modem_NativeModemBits_getDataSetReady
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
