/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serial4j_core_terminal_control_NativeTerminalFlags_LocalFlags */

#ifndef _Included_com_serial4j_core_terminal_control_NativeTerminalFlags_LocalFlags
#define _Included_com_serial4j_core_terminal_control_NativeTerminalFlags_LocalFlags
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_LocalFlags
 * Method:    getEchoInputCharacters
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024LocalFlags_getEchoInputCharacters
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_LocalFlags
 * Method:    getEchoControlCharacters
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024LocalFlags_getEchoControlCharacters
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_LocalFlags
 * Method:    getEchoErase
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024LocalFlags_getEchoErase
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_LocalFlags
 * Method:    getEchoKill
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024LocalFlags_getEchoKill
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_LocalFlags
 * Method:    getDisableNewLineAfterEchoKill
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024LocalFlags_getDisableNewLineAfterEchoKill
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_LocalFlags
 * Method:    getEchoNewLine
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024LocalFlags_getEchoNewLine
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_LocalFlags
 * Method:    getEchoDeletedCharactersBackward
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024LocalFlags_getEchoDeletedCharactersBackward
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_LocalFlags
 * Method:    getOutputBeingFlushed
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024LocalFlags_getOutputBeingFlushed
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_LocalFlags
 * Method:    getCanonicalModeInput
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024LocalFlags_getCanonicalModeInput
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_LocalFlags
 * Method:    getEnableExtendedProcessingOfInput
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024LocalFlags_getEnableExtendedProcessingOfInput
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_LocalFlags
 * Method:    getEnableSignalGeneratingCharacters
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024LocalFlags_getEnableSignalGeneratingCharacters
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_LocalFlags
 * Method:    getDisableFlushing
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024LocalFlags_getDisableFlushing
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_LocalFlags
 * Method:    getRedisplayPendingInput
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024LocalFlags_getRedisplayPendingInput
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_LocalFlags
 * Method:    getGenerateTerminateSignalForBackgroundProcess
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024LocalFlags_getGenerateTerminateSignalForBackgroundProcess
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_LocalFlags
 * Method:    getCanonicalPresentation
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024LocalFlags_getCanonicalPresentation
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
