/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serial4j_core_terminal_NativeFileAccessPermissions */

#ifndef _Included_com_serial4j_core_terminal_NativeFileAccessPermissions
#define _Included_com_serial4j_core_terminal_NativeFileAccessPermissions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serial4j_core_terminal_NativeFileAccessPermissions
 * Method:    fileChmod
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_NativeFileAccessPermissions_fileChmod
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_serial4j_core_terminal_NativeFileAccessPermissions
 * Method:    getGrantReadByOwner
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_NativeFileAccessPermissions_getGrantReadByOwner
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_NativeFileAccessPermissions
 * Method:    getGrantWriteByOwner
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_NativeFileAccessPermissions_getGrantWriteByOwner
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_NativeFileAccessPermissions
 * Method:    getGrantExecuteByOwner
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_NativeFileAccessPermissions_getGrantExecuteByOwner
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_NativeFileAccessPermissions
 * Method:    getGrantFullPermissions
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_NativeFileAccessPermissions_getGrantFullPermissions
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
