/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags_MaskBits */

#ifndef _Included_com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags_MaskBits
#define _Included_com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags_MaskBits
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags_MaskBits
 * Method:    getBackspace0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_00024MaskBits_getBackspace0
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags_MaskBits
 * Method:    getBackspace1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_00024MaskBits_getBackspace1
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags_MaskBits
 * Method:    getCarriageReturn0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_00024MaskBits_getCarriageReturn0
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags_MaskBits
 * Method:    getCarriageReturn1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_00024MaskBits_getCarriageReturn1
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags_MaskBits
 * Method:    getCarriageReturn2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_00024MaskBits_getCarriageReturn2
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags_MaskBits
 * Method:    getCarriageReturn3
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_00024MaskBits_getCarriageReturn3
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags_MaskBits
 * Method:    getFormFeed0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_00024MaskBits_getFormFeed0
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags_MaskBits
 * Method:    getFormFeed1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_00024MaskBits_getFormFeed1
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags_MaskBits
 * Method:    getNewLineDelay0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_00024MaskBits_getNewLineDelay0
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags_MaskBits
 * Method:    getNewLineDelay1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_00024MaskBits_getNewLineDelay1
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags_MaskBits
 * Method:    getHorizontalTabDelay0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_00024MaskBits_getHorizontalTabDelay0
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags_MaskBits
 * Method:    getHorizontalTabDelay1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_00024MaskBits_getHorizontalTabDelay1
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags_MaskBits
 * Method:    getHorizontalTabDelay2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_00024MaskBits_getHorizontalTabDelay2
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags_MaskBits
 * Method:    getHorizontalTabDelay3
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_00024MaskBits_getHorizontalTabDelay3
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags_MaskBits
 * Method:    getVerticalTabDelay0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_00024MaskBits_getVerticalTabDelay0
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_OutputFlags_MaskBits
 * Method:    getVerticalTabDelay1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024OutputFlags_00024MaskBits_getVerticalTabDelay1
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
