/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serial4j_core_terminal_NativeTerminalDevice_FileSeekCriterion */

#ifndef _Included_com_serial4j_core_terminal_NativeTerminalDevice_FileSeekCriterion
#define _Included_com_serial4j_core_terminal_NativeTerminalDevice_FileSeekCriterion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serial4j_core_terminal_NativeTerminalDevice_FileSeekCriterion
 * Method:    getSeekFromStart
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_NativeTerminalDevice_00024FileSeekCriterion_getSeekFromStart
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_NativeTerminalDevice_FileSeekCriterion
 * Method:    getSeekFromCurrent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_NativeTerminalDevice_00024FileSeekCriterion_getSeekFromCurrent
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_NativeTerminalDevice_FileSeekCriterion
 * Method:    getSeekFromEnd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_NativeTerminalDevice_00024FileSeekCriterion_getSeekFromEnd
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
