/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serial4j_core_terminal_control_NativeTerminalFlags_InputFlags */

#ifndef _Included_com_serial4j_core_terminal_control_NativeTerminalFlags_InputFlags
#define _Included_com_serial4j_core_terminal_control_NativeTerminalFlags_InputFlags
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_InputFlags
 * Method:    getSignalInterrupt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024InputFlags_getSignalInterrupt
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_InputFlags
 * Method:    getMapCarriageReturnToNewLine
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024InputFlags_getMapCarriageReturnToNewLine
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_InputFlags
 * Method:    getIgnoreBreakCondition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024InputFlags_getIgnoreBreakCondition
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_InputFlags
 * Method:    getIgnoreCarriageReturn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024InputFlags_getIgnoreCarriageReturn
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_InputFlags
 * Method:    getIgnoreCharsWithParityErrors
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024InputFlags_getIgnoreCharsWithParityErrors
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_InputFlags
 * Method:    getRingBell
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024InputFlags_getRingBell
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_InputFlags
 * Method:    getMapNewLineToCarriageReturn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024InputFlags_getMapNewLineToCarriageReturn
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_InputFlags
 * Method:    getEnableParityChecking
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024InputFlags_getEnableParityChecking
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_InputFlags
 * Method:    getStripHighBit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024InputFlags_getStripHighBit
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_InputFlags
 * Method:    getInputIsUnicode8
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024InputFlags_getInputIsUnicode8
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_InputFlags
 * Method:    getMapUppercaseToLowercase
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024InputFlags_getMapUppercaseToLowercase
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_InputFlags
 * Method:    getAllowToRestartStoppedOutput
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024InputFlags_getAllowToRestartStoppedOutput
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_InputFlags
 * Method:    getEnableInputFlowControl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024InputFlags_getEnableInputFlowControl
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_InputFlags
 * Method:    getEnableOutputFlowControl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024InputFlags_getEnableOutputFlowControl
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_InputFlags
 * Method:    getMarkParityErrors
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024InputFlags_getMarkParityErrors
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
