/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags */

#ifndef _Included_com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags
#define _Included_com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags
 * Method:    getBaudMask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_getBaudMask
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags
 * Method:    getExtendedBaudMask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_getExtendedBaudMask
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags
 * Method:    getInputBaudRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_getInputBaudRate
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags
 * Method:    getIgnoreModemStatusLines
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_getIgnoreModemStatusLines
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags
 * Method:    getUseStickParity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_getUseStickParity
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags
 * Method:    getAllowInput
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_getAllowInput
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags
 * Method:    getEnableHardwareFlowControl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_getEnableHardwareFlowControl
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags
 * Method:    getCharacterSizeMask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_getCharacterSizeMask
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags
 * Method:    getUse2StopBitsPerCharacter
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_getUse2StopBitsPerCharacter
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags
 * Method:    getHangUpOnLastClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_getHangUpOnLastClose
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags
 * Method:    getParityEnable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_getParityEnable
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_terminal_control_NativeTerminalFlags_ControlFlags
 * Method:    getUseOddParity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_terminal_control_NativeTerminalFlags_00024ControlFlags_getUseOddParity
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
