/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.serial4j;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        
    }
}
