# Serial4j-v1 low-level workflow
name: Build Serial4j-v1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:

  # enables the manual run button
  workflow_dispatch:

jobs:  
  build-serial4jv1:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Setup java environment
          run:  chmod +rwx ./launch-environment-setup.sh && ./launch-environment-setup.sh 
          
        - name: Compile Serial4j-v1
          run:  chmod +rwx ./build/compile/compile.sh && ./build/compile/compile.sh
        
        - name: Assemble Serial4j-v1
          run:  chmod +rwx ./build/assemble/assemble.sh && ./build/assemble/assemble.sh         
        
        - name: Run Serial4j-v1 Testcase
          run:  chmod +rwx ./output/run/run.sh && ./output/run/run.sh
