# Serial4j-v1 low-level workflow
name: Build, publish and deploy Serial4j-v1

on:
  release:
    types: ['published', 'prereleased']
    
  # enables the manual run button
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:  
  build-deploy-serial4jv1:
      runs-on: ubuntu-latest
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - uses: actions/checkout@v3
        - name: Clone and checkout to the repository
          run: echo "Checking out to the repository ..."
          
        - name: Setup java environment
          run:  chmod +rwx ./launch-environment-setup.sh && ./launch-environment-setup.sh 
          
        - name: Compile Serial4j-v1
          run:  chmod +rwx ./build/compile/compile.sh && ./build/compile/compile.sh
        
        - name: Assemble Serial4j-v1
          run:  chmod +rwx ./build/assemble/assemble.sh && ./build/assemble/assemble.sh         
        
        - name: Run Serial4j-v1 Testcase
          run:  chmod +rwx ./output/run/run.sh && ./output/run/run.sh
          
        - name: Publish to apache maven
          env:
            GITHUB_USERNAME: ${{ secrets.USERNAME }}
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
          run: chmod +rwx ./maven-publish.sh && ./maven-publish.sh
          
        - name: Setup Pages
          uses: actions/configure-pages@v2
          
        - name: Build docs with Jekyll
          uses: actions/jekyll-build-pages@v1
          with:
            source: ./docs
            destination: ./_site
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v1
        
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v1
